src/views/admin_routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from src.__init__ import db
from src.models.models import User
from src.forms.webforms import RegistrationForm, SearchForm

admin = Blueprint("admin", __name__)


@admin.route('/dashboard')
@login_required
def dashboard():
    form = SearchForm()
    our_users = User.query.all()

    return render_template('admin/dashboard.html', user=current_user, our_users=our_users, form=form)


@admin.route('/profile/<int:id>', methods=['GET', 'POST'])
@login_required
def profile(id):
    form = RegistrationForm()
    user_to_update = User.query.get_or_404(id)

    if request.method == 'POST':
        user_to_update.name = request.form['name']
        user_to_update.surname = request.form['surname']
        user_to_update.email = request.form['email']

        try:
            db.session.commit()
            flash("User Updated Succesfully")

            return render_template('admin/dashboard.html', form=form, user=user_to_update, id=id)

        except:
            flash("Encountered an Error!...Try Again!")

            return render_template('admin/profile.html', form=form, user=user_to_update, id=id)

    else:

        return render_template("admin/profile.html", form=form, user=user_to_update, id=id)


@admin.route('/delete/<int:id>')
@login_required
def delete(id):
    if id == current_user.id:
        delete_user = User.query.get_or_404(id)
        form = RegistrationForm

        try:
            db.session.delete(delete_user)
            db.session.commit()

            flash("User Deleted Succesfully!")
            return redirect(url_for('auth.login'))

        except:
            flash("Whoops! Encountered a problem deleting the user")
            return render_template('admin/profile.html', form=form)

    else:
        flash("Requires authorization!! You are not the Admin of This Profile..")
        return redirect(url_for('admin.dashboard'))


# @admin.route('/stats')
# @login_required
# def statistics():
#     form = SearchForm()
    
#     return render_template("admin/statistics.html", user=current_user, form=form)

src/views/auth_routes.py
from flask import Blueprint, request, render_template, url_for, redirect, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user


from src.forms.webforms import RegistrationForm, LoginForm
from src.__init__ import db
from src.models.models import User


auth = Blueprint("auth", __name__)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    """Registers the User."""

    form = RegistrationForm()

    # Validate Form
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is None:
            # Hash the password
            hashed_password = generate_password_hash(
                form.password1.data, "sha256")

            new_user = User(name=form.name.data, surname=form.surname.data,
                            email=form.email.data, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()

            flash("Account Created Successfully!")
            return redirect(url_for('auth.login'))

        else:
            flash("Username already exists!! Choose another Username")

        form.name.data = ''
        form.surname.data = ''
        form.email.data = ''
        form.password1.data = ''

    return render_template('auth/register.html', form=form, user=current_user)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """Logs In the User."""

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            # Check the password hash if it matches the typed password
            if check_password_hash(user.password, form.password.data):
                login_user(user)

                if user.id == 1 or user.id == 2:
                    flash("Hello Admin")
                    return redirect(url_for('admin.dashboard'))
                else:
                    flash("Signed In Successfully")
                    return redirect(url_for('member.dashboard'))
            else:
                flash("Incorrect password! - Try Again")
        else:
            flash("Incorrect Username. Try Again")

    return render_template('auth/login.html', form=form, user=current_user)


@auth.route('/logout')
@login_required
def logout():
    """Logs out the user."""

    logout_user()
    flash("You have been Logged out")
    return redirect(url_for('auth.login'))

src/views/member_routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, make_response
from flask_login import login_required, current_user
from src.forms.webforms import RegistrationForm, SearchForm
from src.models.models import db, User, Saved
from datetime import datetime

member = Blueprint("member", __name__)


@member.route('/dashboard')
@login_required
def dashboard():
    form = SearchForm()
    
    return render_template("member/dashboard.html", user=current_user, form=form)


@member.route('/profile/<int:id>', methods=['GET', 'POST'])
@login_required
def profile(id):
    form = RegistrationForm()
    user_to_update = User.query.get_or_404(id)

    if id == current_user.id:
        if request.method == 'POST':
            user_to_update.name = request.form['name']
            user_to_update.surname = request.form['surname']
            user_to_update.email = request.form['email']

            try:
                db.session.commit()
                flash("User Updated Succesfully")

                return render_template('member/dashboard.html', form=form, user=user_to_update, id=id)

            except:
                flash("Encountered an Error!...Try Again!")

                return render_template('member/profile.html', form=form, user=user_to_update, id=id)

        else:

            return render_template("member/profile.html", form=form, user=user_to_update, id=id)
    else:
        flash("Not your profile...")
        return redirect(url_for('member.dashboard'))


@member.route('/delete/<int:id>')
@login_required
def delete(id):

    if id == current_user.id:
        delete_user = User.query.get_or_404(id)
        form = RegistrationForm

        try:
            db.session.delete(delete_user)
            db.session.commit()

            flash("User Deleted Succesfully!")
            return redirect(url_for('auth.login'))

        except:
            flash("Whoops! Encountered a problem deleting the user")
            return render_template('member/profile.html', form=form)

    else:
        flash("Requires authorization!! You are not an Admin..")
        return redirect(url_for('dashboard'))


@member.route('/saved')
@login_required
def saved():
    form = SearchForm()
    saved_jobs = Saved.query.order_by(Saved.id)
    
    return render_template("member/saved.html", user=current_user, form=form, saved_jobs=saved_jobs)


@member.route('/deadlines')
@login_required
def deadlines():
    form = SearchForm()
    saved_jobs = Saved.query.order_by(Saved.closing_date)
    
    return render_template("member/deadlines.html", user=current_user, form=form, saved_jobs=saved_jobs)


@member.route("/save", methods=["POST"])
@login_required
def save():
    req = request.get_json()
    
    title = req["title"]
    description = req["description"]
    link = req["link"]
    closing_date = req["closing_date"] + " 00:00:00"
    closing_date = datetime.strptime(closing_date, '%Y-%m-%d %H:%M:%S')

    job = Saved(job_title=title, description=description, link=link, applied_to=False, closing_date=closing_date, user_id=current_user.id)
    db.session.add(job)
    db.session.commit()

    res = make_response(jsonify({"success": "fa-solid fa-bookmark"}), 200)

    return res


@member.route('/saved/')
@login_required
def delete_saved():
    form = SearchForm()
    delete_saved_job = Saved.query.order_by(Saved.id).first()
    
    if current_user.id == delete_saved_job.user_id:
    
        # if delete_saved_job:
        try:
            db.session.delete(delete_saved_job)
            db.session.commit()
            flash("Deleted successfully!")
                
            saved_jobs = Saved.query.order_by(Saved.closing_date)
            return render_template('member/saved.html', user=current_user, form=form, id=id, saved_jobs=saved_jobs)
        except:
            flash("An Error Occurred...failed to delete selection.")
            saved_jobs = Saved.query.order_by(Saved.closing_date)
            return render_template('member/saved.html', user=current_user, form=form, id=id, saved_jobs=saved_jobs)
        # else:
        #     flash("Could not perform operation, No record was found.")
        #     saved_jobs = Saved.query.order_by(Saved.closing_date)
        #     return render_template('member/saved.html', user=current_user, form=form, id=id, saved_jobs=saved_jobs)
    
    else:
        flash("Unauthorized Access!!!!")
        return redirect(url_for('auth.logout'))

src/views/public_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from src.forms.webforms import SearchForm
from src.web_scraper.scraper import Search_careerjunction

public = Blueprint("public", __name__)


@public.route('/')
def home():

    return render_template('public/home.html', user=current_user)


@public.context_processor
def base():
    form = SearchForm()
    return dict(form=form)


@public.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    
    results = Search_careerjunction(request.form.get("search"))
        
    return render_template("public/search.html", user=current_user, form=form, results=results)

    # else:
    #     return render_template("public/search.html", user=current_user, form=form)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <!-- Our CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
  </head>

  <body>
    {% include 'navbar.html' %}
    <br />
    {% for message in get_flashed_messages() %}
    
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

    <div class="container">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

src/templates/base_search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <script src="https://kit.fontawesome.com/2ac6982717.js" crossorigin="anonymous"></script>
    <style>
        .searchbox {
            float: left;
        }
    
        input[type=text] {
            padding: 6px;
            margin-top: 8px;
            font-size: 17px;
            border: none;
        }
    
        .searchbox button {
    
            padding: 8px;
            margin-top: 10px;
            margin-left: 10px;
            background: orange;
            font-size: 20px;
            border: none;
            cursor: pointer;
        }
    
        .searchbox button:hover {
            background: blue;
        }
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous" />
    <!-- Our CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<body>
    {% include 'navbar.html' %}
    <br />

    <div class="container">{% block content %}{% endblock %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <a class="navbar-brand" href="{{ url_for('public.home') }}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        {% if user.id == 1 or user.id == 2 %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('admin.dashboard') }}">Dashboard</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"
            href="{{ url_for('admin.profile', id=current_user.id) }}">Profile</a>
        </li>

        {% else %}

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('member.dashboard') }}">Dashboard</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-curren="page" href="{{ url_for('member.saved') }}">Saved</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('member.deadlines') }}">Deadlines</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page"
            href="{{ url_for('member.profile', id=current_user.id) }}">Profile</a>
        </li>

        {% endif %}

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('auth.register') }}">Sign-Up</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('auth.login') }}">Sign-in</a>
        </li>
        {% endif %}
      </ul>
      <form method="POST" action="{{ url_for('public.search') }}" class="d-flex" role="search">
        {{ form.hidden_tag() }}
        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search" />
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>